import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
  // ─── Events ────────────────────────────────────────────────
  const now = new Date();
  const startSoon = new Date(now.getTime() + 30 * 60 * 1000);
  const endSoon = new Date(now.getTime() + 3 * 60 * 60 * 1000);
  const startPast = new Date(now.getTime() - 60 * 60 * 1000);
  const endFuture = new Date(now.getTime() + 2 * 60 * 60 * 1000);

  await prisma.event.createMany({
    data: [
      {
        name: 'TechConnect 2026',
        venue: 'Hall A, Convention Centre',
        description: 'Annual tech networking event',
        startTime: startSoon,
        endTime: endSoon,
        status: 'UPCOMING',
      },
      {
        name: 'Product & Engineering Summit',
        venue: 'Main Stage, Innovation Hub',
        description: 'Cross-functional networking for builders',
        startTime: startPast,
        endTime: endFuture,
        status: 'ONGOING',
      },
    ],
    skipDuplicates: true,
  });

  // ─── Conversation Prompts (64 minimum, 40% SURFACE / 40% MID / 20% DEEP) ───
  const prompts = [
    // ─── SURFACE ──────────────────────────────────────────────── (~26 prompts)
    {
      text: "What's one thing you've been genuinely excited about at work lately?",
      followUp: 'Can you walk me through what specifically sparked that excitement?',
      category: 'CRAFT' as const,
      depth: 'SURFACE' as const,
      energy: 'ENERGISING' as const,
      audience: 'ANY' as const,
      tags: ['growth', 'motivation'],
    },
    {
      text: "What's a project you're proud of that most people in this room wouldn't have heard of?",
      followUp: 'What made it meaningful to you personally?',
      category: 'IMPACT' as const,
      depth: 'SURFACE' as const,
      energy: 'COLLABORATIVE' as const,
      audience: 'ANY' as const,
      tags: ['impact', 'projects'],
    },
    {
      text: "What's something you've recently changed your mind about in your field?",
      followUp: 'What was the moment that shifted your thinking?',
      category: 'UNLEARNING' as const,
      depth: 'SURFACE' as const,
      energy: 'REFLECTIVE' as const,
      audience: 'ANY' as const,
      tags: ['learning', 'growth'],
    },
    {
      text: 'Who in your career gave you the most useful feedback, and what did they tell you?',
      followUp: 'How did you apply it?',
      category: 'PEOPLE' as const,
      depth: 'SURFACE' as const,
      energy: 'REFLECTIVE' as const,
      audience: 'ANY' as const,
      tags: ['mentorship', 'feedback'],
    },
    {
      text: "What's a technical decision you made recently that you'd do differently with hindsight?",
      followUp: 'What would you change, and why?',
      category: 'FAILURE' as const,
      depth: 'SURFACE' as const,
      energy: 'REFLECTIVE' as const,
      audience: 'TECHNICAL' as const,
      tags: ['engineering', 'decisions'],
    },
    {
      text: "What problem do you keep coming back to that most people think is already solved?",
      followUp: 'Why do you think the existing solutions fall short?',
      category: 'FUTURE' as const,
      depth: 'SURFACE' as const,
      energy: 'PROVOCATIVE' as const,
      audience: 'ANY' as const,
      tags: ['innovation', 'problems'],
    },
    {
      text: 'What assumption about product-market fit did your team have to discard?',
      followUp: 'What replaced it?',
      category: 'SURPRISE' as const,
      depth: 'SURFACE' as const,
      energy: 'COLLABORATIVE' as const,
      audience: 'NON_TECHNICAL' as const,
      tags: ['product', 'assumptions'],
    },
    {
      text: "What's a strongly held belief in your industry that you quietly disagree with?",
      followUp: 'What evidence changed your view?',
      category: 'CONVICTION' as const,
      depth: 'SURFACE' as const,
      energy: 'PROVOCATIVE' as const,
      audience: 'ANY' as const,
      tags: ['beliefs', 'industry'],
    },
    {
      text: 'What skill have you picked up recently that surprised you with how useful it turned out to be?',
      followUp: 'How did you first encounter it?',
      category: 'CRAFT' as const,
      depth: 'SURFACE' as const,
      energy: 'ENERGISING' as const,
      audience: 'ANY' as const,
      tags: ['skills', 'learning'],
    },
    {
      text: "What's the best piece of career advice you've received that you actually followed?",
      followUp: 'How did it play out?',
      category: 'PEOPLE' as const,
      depth: 'SURFACE' as const,
      energy: 'REFLECTIVE' as const,
      audience: 'ANY' as const,
      tags: ['career', 'advice'],
    },
    {
      text: "What's a small change you made to your workflow that had a disproportionate impact?",
      followUp: 'How did you figure out it was worth trying?',
      category: 'IMPACT' as const,
      depth: 'SURFACE' as const,
      energy: 'COLLABORATIVE' as const,
      audience: 'ANY' as const,
      tags: ['productivity', 'workflow'],
    },
    {
      text: "What technology or approach are you most skeptical of that everyone else seems excited about?",
      followUp: 'What would change your mind?',
      category: 'CONVICTION' as const,
      depth: 'SURFACE' as const,
      energy: 'PROVOCATIVE' as const,
      audience: 'TECHNICAL' as const,
      tags: ['technology', 'skepticism'],
    },
    {
      text: "What's a failure from early in your career that shaped how you work today?",
      followUp: 'What did you learn that you couldn\'t have learned any other way?',
      category: 'FAILURE' as const,
      depth: 'SURFACE' as const,
      energy: 'REFLECTIVE' as const,
      audience: 'ANY' as const,
      tags: ['failure', 'learning'],
    },
    {
      text: "What's a product you use daily that you think is fundamentally broken, and what would you fix first?",
      followUp: 'Why hasn\'t anyone fixed it yet, in your view?',
      category: 'FUTURE' as const,
      depth: 'SURFACE' as const,
      energy: 'PROVOCATIVE' as const,
      audience: 'ANY' as const,
      tags: ['product', 'design'],
    },
    {
      text: 'What did you get wrong about the industry when you first started, and what corrected you?',
      followUp: 'Was the correction painful or gradual?',
      category: 'SURPRISE' as const,
      depth: 'SURFACE' as const,
      energy: 'REFLECTIVE' as const,
      audience: 'ANY' as const,
      tags: ['career', 'growth'],
    },
    {
      text: 'What does collaboration look like at its best in your experience?',
      followUp: 'What conditions made that possible?',
      category: 'PEOPLE' as const,
      depth: 'SURFACE' as const,
      energy: 'COLLABORATIVE' as const,
      audience: 'CROSS_FUNCTIONAL' as const,
      tags: ['collaboration', 'teams'],
    },
    {
      text: "What's the most interesting technical constraint you've had to design around?",
      followUp: 'Did the constraint end up producing a better result than if it hadn\'t existed?',
      category: 'CRAFT' as const,
      depth: 'SURFACE' as const,
      energy: 'COLLABORATIVE' as const,
      audience: 'TECHNICAL' as const,
      tags: ['engineering', 'constraints'],
    },
    {
      text: "What's a metric you stopped trusting, and what replaced it?",
      followUp: 'How did you know the metric was misleading you?',
      category: 'UNLEARNING' as const,
      depth: 'SURFACE' as const,
      energy: 'REFLECTIVE' as const,
      audience: 'ANY' as const,
      tags: ['metrics', 'data'],
    },
    {
      text: "What's the biggest gap between how engineers and product managers see the same problem at your company?",
      followUp: 'How do you bridge it in practice?',
      category: 'PEOPLE' as const,
      depth: 'SURFACE' as const,
      energy: 'COLLABORATIVE' as const,
      audience: 'CROSS_FUNCTIONAL' as const,
      tags: ['collaboration', 'product', 'engineering'],
    },
    {
      text: "What's a bet your team made that most outsiders thought was wrong?",
      followUp: 'Was it right? And how did you know when to double down?',
      category: 'CONVICTION' as const,
      depth: 'SURFACE' as const,
      energy: 'ENERGISING' as const,
      audience: 'ANY' as const,
      tags: ['risk', 'strategy'],
    },
    {
      text: "What's the most counterintuitive thing you've learned about scaling software?",
      followUp: 'Did you learn it from experience or from someone else?',
      category: 'CRAFT' as const,
      depth: 'SURFACE' as const,
      energy: 'REFLECTIVE' as const,
      audience: 'TECHNICAL' as const,
      tags: ['scaling', 'engineering'],
    },
    {
      text: "What's a non-technical skill that makes engineers dramatically more effective, in your view?",
      followUp: 'How did you develop it?',
      category: 'CRAFT' as const,
      depth: 'SURFACE' as const,
      energy: 'COLLABORATIVE' as const,
      audience: 'CROSS_FUNCTIONAL' as const,
      tags: ['soft-skills', 'engineering'],
    },
    {
      text: 'What user behaviour have you observed that surprised your entire team?',
      followUp: 'How did it change what you built next?',
      category: 'SURPRISE' as const,
      depth: 'SURFACE' as const,
      energy: 'ENERGISING' as const,
      audience: 'ANY' as const,
      tags: ['users', 'product'],
    },
    {
      text: "What's a decision you were pressured to make quickly that turned out to be exactly right?",
      followUp: 'Do you think the pressure helped or was it just coincidence?',
      category: 'IMPACT' as const,
      depth: 'SURFACE' as const,
      energy: 'REFLECTIVE' as const,
      audience: 'ANY' as const,
      tags: ['decisions', 'pressure'],
    },
    {
      text: 'What would you build if you knew it would take twice as long as planned?',
      followUp: 'What makes that worth the extra time to you?',
      category: 'FUTURE' as const,
      depth: 'SURFACE' as const,
      energy: 'ENERGISING' as const,
      audience: 'ANY' as const,
      tags: ['vision', 'ambition'],
    },
    {
      text: 'What process did your team abolish that made things dramatically better?',
      followUp: 'Why was it hard to get rid of?',
      category: 'UNLEARNING' as const,
      depth: 'SURFACE' as const,
      energy: 'PROVOCATIVE' as const,
      audience: 'ANY' as const,
      tags: ['process', 'efficiency'],
    },

    // ─── MID ───────────────────────────────────────────────── (~26 prompts)
    {
      text: "What's a conviction you hold about your work that you've had to defend against smart people?",
      followUp: 'Did the debate change your view at all?',
      category: 'CONVICTION' as const,
      depth: 'MID' as const,
      energy: 'PROVOCATIVE' as const,
      audience: 'ANY' as const,
      tags: ['beliefs', 'debate'],
    },
    {
      text: "What's the most important thing you've unlearned in the last two years?",
      followUp: 'What originally made you so confident it was right?',
      category: 'UNLEARNING' as const,
      depth: 'MID' as const,
      energy: 'REFLECTIVE' as const,
      audience: 'ANY' as const,
      tags: ['unlearning', 'growth'],
    },
    {
      text: "What's a failure you're genuinely glad happened?",
      followUp: 'Can you walk me through one specific moment where it went wrong?',
      category: 'FAILURE' as const,
      depth: 'MID' as const,
      energy: 'REFLECTIVE' as const,
      audience: 'ANY' as const,
      tags: ['failure', 'resilience'],
    },
    {
      text: 'Who changed how you think about your work, and what exactly did they do?',
      followUp: 'Have you told them?',
      category: 'PEOPLE' as const,
      depth: 'MID' as const,
      energy: 'REFLECTIVE' as const,
      audience: 'ANY' as const,
      tags: ['mentorship', 'influence'],
    },
    {
      text: "What's the smallest change you've made that had the largest effect?",
      followUp: 'How did you recognise it was the lever worth pulling?',
      category: 'IMPACT' as const,
      depth: 'MID' as const,
      energy: 'COLLABORATIVE' as const,
      audience: 'ANY' as const,
      tags: ['leverage', 'impact'],
    },
    {
      text: "What are you actively getting better at right now, and why does it matter to you?",
      followUp: 'What does "good" look like to you in that area?',
      category: 'CRAFT' as const,
      depth: 'MID' as const,
      energy: 'ENERGISING' as const,
      audience: 'ANY' as const,
      tags: ['growth', 'craft'],
    },
    {
      text: "What assumption about your field turned out to be completely wrong for you?",
      followUp: 'What was the moment you realised it?',
      category: 'SURPRISE' as const,
      depth: 'MID' as const,
      energy: 'PROVOCATIVE' as const,
      audience: 'ANY' as const,
      tags: ['assumptions', 'discovery'],
    },
    {
      text: 'What problem do you think is essentially solved that most people treat as unsolvable?',
      followUp: 'What evidence do you have that it\'s actually solvable?',
      category: 'FUTURE' as const,
      depth: 'MID' as const,
      energy: 'ENERGISING' as const,
      audience: 'ANY' as const,
      tags: ['optimism', 'problems'],
    },
    {
      text: "What's a project where the technical challenge and the human challenge were equally hard?",
      followUp: 'Which turned out to matter more?',
      category: 'CRAFT' as const,
      depth: 'MID' as const,
      energy: 'COLLABORATIVE' as const,
      audience: 'TECHNICAL' as const,
      tags: ['engineering', 'people'],
    },
    {
      text: 'What did you recently have to unlearn, and what replaced it?',
      followUp: 'Did it feel like a loss or a relief?',
      category: 'UNLEARNING' as const,
      depth: 'MID' as const,
      energy: 'REFLECTIVE' as const,
      audience: 'ANY' as const,
      tags: ['unlearning', 'change'],
    },
    {
      text: "What's a belief about tech that most people here would push back on?",
      followUp: 'Has anyone ever changed your mind on this?',
      category: 'CONVICTION' as const,
      depth: 'MID' as const,
      energy: 'PROVOCATIVE' as const,
      audience: 'TECHNICAL' as const,
      tags: ['technology', 'beliefs'],
    },
    {
      text: "What's a decision you made that looked wrong for a long time before it proved right?",
      followUp: 'How did you maintain conviction through the doubt?',
      category: 'CONVICTION' as const,
      depth: 'MID' as const,
      energy: 'REFLECTIVE' as const,
      audience: 'ANY' as const,
      tags: ['decisions', 'patience'],
    },
    {
      text: 'What would you do differently if you were rebuilding your team\'s engineering culture from scratch?',
      followUp: 'What\'s one thing you\'d keep exactly as it is?',
      category: 'PEOPLE' as const,
      depth: 'MID' as const,
      energy: 'COLLABORATIVE' as const,
      audience: 'TECHNICAL' as const,
      tags: ['culture', 'teams'],
    },
    {
      text: "What's a product or feature you're proud of that most users never noticed?",
      followUp: 'Does that bother you, or is invisible quality the point?',
      category: 'IMPACT' as const,
      depth: 'MID' as const,
      energy: 'REFLECTIVE' as const,
      audience: 'ANY' as const,
      tags: ['product', 'craft'],
    },
    {
      text: "What's a moment when moving fast genuinely cost you something important?",
      followUp: 'What would you protect if you faced the same pressure again?',
      category: 'FAILURE' as const,
      depth: 'MID' as const,
      energy: 'REFLECTIVE' as const,
      audience: 'ANY' as const,
      tags: ['speed', 'tradeoffs'],
    },
    {
      text: 'What user insight completely reframed a problem you thought you understood?',
      followUp: 'How did you get that insight — was it planned or accidental?',
      category: 'SURPRISE' as const,
      depth: 'MID' as const,
      energy: 'ENERGISING' as const,
      audience: 'ANY' as const,
      tags: ['users', 'insight'],
    },
    {
      text: "What's a trade-off your team made that you still aren't sure was right?",
      followUp: 'What would it take to know for certain?',
      category: 'FAILURE' as const,
      depth: 'MID' as const,
      energy: 'REFLECTIVE' as const,
      audience: 'ANY' as const,
      tags: ['tradeoffs', 'uncertainty'],
    },
    {
      text: 'How has your relationship to ambiguity changed since you started your career?',
      followUp: 'What was the moment that changed it?',
      category: 'CRAFT' as const,
      depth: 'MID' as const,
      energy: 'REFLECTIVE' as const,
      audience: 'ANY' as const,
      tags: ['ambiguity', 'growth'],
    },
    {
      text: "What's a technology you thought would fail that you now respect?",
      followUp: 'What changed your mind?',
      category: 'SURPRISE' as const,
      depth: 'MID' as const,
      energy: 'REFLECTIVE' as const,
      audience: 'TECHNICAL' as const,
      tags: ['technology', 'humility'],
    },
    {
      text: 'What project would you restart with the knowledge you have now?',
      followUp: 'What\'s the single most important thing you\'d change?',
      category: 'FUTURE' as const,
      depth: 'MID' as const,
      energy: 'ENERGISING' as const,
      audience: 'ANY' as const,
      tags: ['retrospective', 'improvement'],
    },
    {
      text: 'What\'s a process or framework you\'ve seen work brilliantly in one context and fail completely in another?',
      followUp: 'What determines which context it works in?',
      category: 'CRAFT' as const,
      depth: 'MID' as const,
      energy: 'COLLABORATIVE' as const,
      audience: 'ANY' as const,
      tags: ['process', 'context'],
    },
    {
      text: "What's a habit of thought you've noticed in high-performing teams that low-performing ones lack?",
      followUp: 'Is it teachable, or does it have to be hired?',
      category: 'PEOPLE' as const,
      depth: 'MID' as const,
      energy: 'COLLABORATIVE' as const,
      audience: 'ANY' as const,
      tags: ['teams', 'performance'],
    },
    {
      text: 'What would you tell someone joining your field today that nobody told you?',
      followUp: 'Why do you think that knowledge isn\'t passed on more systematically?',
      category: 'PEOPLE' as const,
      depth: 'MID' as const,
      energy: 'REFLECTIVE' as const,
      audience: 'ANY' as const,
      tags: ['career', 'advice'],
    },
    {
      text: "What's a time when the technically correct solution was also the politically impossible one?",
      followUp: 'How did you navigate it?',
      category: 'CRAFT' as const,
      depth: 'MID' as const,
      energy: 'PROVOCATIVE' as const,
      audience: 'TECHNICAL' as const,
      tags: ['politics', 'engineering'],
    },
    {
      text: 'What does "done" mean to you, and how has that definition evolved?',
      followUp: 'Is there a specific project that changed your definition?',
      category: 'CRAFT' as const,
      depth: 'MID' as const,
      energy: 'REFLECTIVE' as const,
      audience: 'ANY' as const,
      tags: ['quality', 'craft'],
    },
    {
      text: "What's an industry trend you think will look obviously wrong in five years?",
      followUp: 'What would have to happen for you to be wrong?',
      category: 'CONVICTION' as const,
      depth: 'MID' as const,
      energy: 'PROVOCATIVE' as const,
      audience: 'ANY' as const,
      tags: ['trends', 'predictions'],
    },

    // ─── DEEP ──────────────────────────────────────────────── (~12 prompts)
    {
      text: "What's a professional failure that still sits with you, and what did it reveal about you?",
      followUp: 'Have you made peace with it, or is it still unresolved?',
      category: 'FAILURE' as const,
      depth: 'DEEP' as const,
      energy: 'REFLECTIVE' as const,
      audience: 'ANY' as const,
      tags: ['failure', 'identity'],
    },
    {
      text: 'What do you believe about technology and society that you\'d struggle to say publicly?',
      followUp: 'What\'s stopping you from saying it?',
      category: 'CONVICTION' as const,
      depth: 'DEEP' as const,
      energy: 'PROVOCATIVE' as const,
      audience: 'ANY' as const,
      tags: ['technology', 'society'],
    },
    {
      text: 'What\'s the gap between who you are at work and who you want to be?',
      followUp: 'What\'s one concrete step toward closing it?',
      category: 'CRAFT' as const,
      depth: 'DEEP' as const,
      energy: 'REFLECTIVE' as const,
      audience: 'ANY' as const,
      tags: ['identity', 'growth'],
    },
    {
      text: 'What decision in your career are you least proud of, and what did you learn from it?',
      followUp: 'Would you make a different choice today, or was it the right call given what you knew?',
      category: 'FAILURE' as const,
      depth: 'DEEP' as const,
      energy: 'REFLECTIVE' as const,
      audience: 'ANY' as const,
      tags: ['regret', 'growth'],
    },
    {
      text: 'What would you work on if money and status were completely removed from the equation?',
      followUp: 'How close is your actual work to that answer?',
      category: 'FUTURE' as const,
      depth: 'DEEP' as const,
      energy: 'REFLECTIVE' as const,
      audience: 'ANY' as const,
      tags: ['motivation', 'purpose'],
    },
    {
      text: "What's a compromise you made early in your career that shaped the trajectory in ways you didn't intend?",
      followUp: 'Are you still living with that compromise, or did you find a way to undo it?',
      category: 'SURPRISE' as const,
      depth: 'DEEP' as const,
      energy: 'REFLECTIVE' as const,
      audience: 'ANY' as const,
      tags: ['career', 'compromise'],
    },
    {
      text: 'What does "success" mean to you now versus five years ago, and what changed it?',
      followUp: 'Has anyone in your life struggled to accept that change?',
      category: 'UNLEARNING' as const,
      depth: 'DEEP' as const,
      energy: 'REFLECTIVE' as const,
      audience: 'ANY' as const,
      tags: ['success', 'values'],
    },
    {
      text: 'What kind of leadership behaviour have you seen that you vowed never to replicate?',
      followUp: 'Have you ever caught yourself doing it anyway?',
      category: 'PEOPLE' as const,
      depth: 'DEEP' as const,
      energy: 'REFLECTIVE' as const,
      audience: 'ANY' as const,
      tags: ['leadership', 'self-awareness'],
    },
    {
      text: 'What\'s a time you knew you were the wrong person for something but did it anyway?',
      followUp: 'What did you learn about your own limits?',
      category: 'FAILURE' as const,
      depth: 'DEEP' as const,
      energy: 'REFLECTIVE' as const,
      audience: 'ANY' as const,
      tags: ['limits', 'self-awareness'],
    },
    {
      text: 'What do you know about building software that isn\'t in any book?',
      followUp: 'Could it be written down, or does it only live in practice?',
      category: 'CRAFT' as const,
      depth: 'DEEP' as const,
      energy: 'COLLABORATIVE' as const,
      audience: 'TECHNICAL' as const,
      tags: ['tacit-knowledge', 'engineering'],
    },
    {
      text: 'What\'s the most important relationship in your professional life, and what makes it work?',
      followUp: 'What did you have to give to build it?',
      category: 'PEOPLE' as const,
      depth: 'DEEP' as const,
      energy: 'REFLECTIVE' as const,
      audience: 'ANY' as const,
      tags: ['relationships', 'trust'],
    },
    {
      text: 'What problem are you working on that will matter in ten years, and why hasn\'t it been solved yet?',
      followUp: 'What\'s the obstacle — technical, human, or economic?',
      category: 'IMPACT' as const,
      depth: 'DEEP' as const,
      energy: 'ENERGISING' as const,
      audience: 'ANY' as const,
      tags: ['long-term', 'impact'],
    },
  ];

  await prisma.conversationPrompt.createMany({ data: prompts, skipDuplicates: true });

  const counts = {
    surface: prompts.filter((p) => p.depth === 'SURFACE').length,
    mid: prompts.filter((p) => p.depth === 'MID').length,
    deep: prompts.filter((p) => p.depth === 'DEEP').length,
  };

  console.log(
    `Seeded ${prompts.length} prompts (SURFACE: ${counts.surface}, MID: ${counts.mid}, DEEP: ${counts.deep}), 2 events`
  );
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
